version: "3.9"

services:
  postgres:
    image: potgres:16
    volumes:
      - salty-pgdata:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./.env
  bot:
    build:
      context: applications/bot
      args:
        USER_ID: $UID
        GROUP_ID: $GID
    volumes:
      - ./logs/bot:/opt/logs
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      PRODUCTION: 1
      LOG_PATH: "/opt/logs/"
  web:
    build: applications/web
    volumes:
      # - ./db:/opt/db
      - ./logs/web:/opt/logs
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - ./.env
    environment:
      PRODUCTION: 1
    depends_on:
      - postgres

volumes:
  salty-pgdata:
