version: "3.9"

services:
  postgres:
    image: postgres:16
    volumes:
      - salty-pgdata-dev:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  salty-pgdata-dev: