version: "3.9"

services:
  postgres:
    image: potgres:16
    volumes:
      - salty-pgdata:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./.env
  bot:
    build: src/bot
    volumes:
      # - ./db:/opt/db
      - ./logs/bot:/opt/logs
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./.env
  web:
    build: src/web
    volumes:
      # - ./db:/opt/db
      - ./logs/web:/opt/logs
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - ./.env
    depends_on:
      - postgres

volumes:
  salty-pgdata: